#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Logs
import os
import sys

top = '.'

def options(opt):
        return

def configure(conf):

        conf.env.CC = "/opt/devkitpro/devkitPPC/bin/powerpc-eabi-gcc"
        conf.env.CXX = "/opt/devkitpro/devkitPPC/bin/powerpc-eabi-g++"

        if conf.env.DEST_OS == 'win32':
                conf.load('winres')

def build(bld):
        source = ['game.cpp']
        includes = '. ../common ../public'
        libs = []
        
        if bld.env.DEST_OS == 'wii':
                source += ['../engine/platform/wii/dll_wii.c', '../public/crtlib.c']
                includes += ' ../engine/common ../engine/client ../engine'

        elif bld.env.DEST_OS != 'win32':
                libs += [ 'DL' ]
        else:
                libs += ['USER32', 'SHELL32']
                source += ['game.rc']

        bld(
                source   = source,
                target   = 'xash3d', # hl.exe
                features = 'c cxx cxxprogram',
                includes = includes,
                use      = libs,
                install_path = bld.env.BINDIR,
                subsystem = bld.env.MSVC_SUBSYSTEM
        )
